import { ServiceKey, type IServiceProvider } from '@pragmatic-tech-ai/mural/runtime'
import { check, checkAgainst, toJSON, Severity, compilePackage, BlobPackageStore, projectAnnotations, type TodlDocument } from '@pragmatic-tech-ai/todl'

import {
    PROJECT_MANIFEST_FILENAME,
    ProducerKind,
    type IProducerProjectFactory,
    type IPresentationProjectFactory,
    type IPublishableProjectFactory,
    type IVersionedProjectFactory,
    type ProjectFileFormat,
    type ProjectManifestEnvelope,
    type PublishResult,
} from '../../../services/projects/project-factory.js'
import { TodlProjectFactory, type ScaffoldFile } from '../../../services/projects/todl-project-factory.js'
import type { Project } from '../../../services/projects/project.js'
import { type IStorage } from '@pragmatic-tech-ai/todl-runtime'
import { StoragePackageSink } from '../../../services/storage/storage-package-sink.js'
import { ensureMetaModelsBackend } from './meta-models-backend.js'
import { META_MODEL_SCAFFOLD } from './meta-model-scaffold.js'
import { collectTodlSources } from '../../../services/todl/todl-sources.js'
import { generatePresentationAssets, stampResourceKeys } from './presentation-generator.js'
import { publishPresentation } from './presentation-publisher.js'
import type { MetaModelManifestFile } from './meta-model-manifest-loader.js'

// The 'meta-model' project type's factory — the meta-model module's contribution
// to the generic ProjectExplorerService (declared via `.projectFactories:` and
// resolved through the ProjectFactoryRegistry). It owns the project lifecycle;
// the `.todl` FILE format is edited by TodlDocumentFactory (resolved by
// extension) — editors own files, this factory owns the project.
//
// It is also publishable (IPublishableProjectFactory): publish validates every
// `.todl` in the project with TODL's check(), and — if clean — writes the
// compiled TodlDocument JSON plus the raw sources into the shared meta-models
// backend under `<id>/<modelVersion>/`, where other project types consume it.
//
// All persistence flows through the project's IStorage (rooted, project-relative
// paths); the factory never sees an absolute path or the raw file system.
interface MetaModelManifest extends ProjectManifestEnvelope
{
    id:           string   // stable publish identity, defaults to slugify(name)
    modelVersion: string   // published version, defaults to '0.1.0'
}

export class MetaModelProjectFactory extends TodlProjectFactory
    implements IPublishableProjectFactory, IPresentationProjectFactory, IProducerProjectFactory, IVersionedProjectFactory
{
    public static readonly Key = new ServiceKey<MetaModelProjectFactory>('MetaModelProjectFactory')
    public static readonly ProjectType = 'meta-model'

    // The autogenerated presentation dictionary + the folder of author overrides
    // it merges. Only the generated file is ever written by this factory.
    private static readonly PRESENTATION_FILE = 'presentation.generated.mu'

    public readonly formats: readonly ProjectFileFormat[] = [
        { extension: '.todl', kind: 'todl', displayName: 'TODL Definition' },
    ]

    constructor(provider: IServiceProvider) { super(provider) }

    protected buildManifest(name: string): ProjectManifestEnvelope
    {
        const manifest: MetaModelManifest = {
            type: MetaModelProjectFactory.ProjectType, name, version: 1,
            id: slugify(name), modelVersion: '0.1.0',
        }
        return manifest
    }

    // The meta-model's own scaffold (its CLAUDE.md + guide + /new-concept); the
    // shared TODL manual + rules are added by the base.
    protected scaffoldContributions(): readonly ScaffoldFile[]
    {
        return META_MODEL_SCAFFOLD
    }

    public async getVersion(storage: IStorage): Promise<string>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        return manifest.modelVersion
    }

    public async setVersion(storage: IStorage, version: string): Promise<void>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        manifest.modelVersion = version
        await storage.WriteText(PROJECT_MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))
    }

    public readonly producerKind = ProducerKind.MetaModel

    // Compile every `.todl` into the base document, exactly as publish does.
    // A meta-model has no bases of its own, so callers pass `bases` (usually []).
    public async compileToDocument(
        storage: IStorage,
        bases: TodlDocument[],
        _provider: IServiceProvider,
    ): Promise<{ doc: TodlDocument; problems: string[] }>
    {
        const sources = await collectTodlSources(storage)
        const { model, diagnostics } = checkAgainst(bases, sources)
        const problems = diagnostics
            .filter((d) => d.severity === Severity.Error)
            .map((d) => d.message)
        return { doc: toJSON(model), problems }
    }

    // Validate every `.todl` together; if clean, emit the compiled model + copy
    // the sources into the meta-models backend under `<id>/<modelVersion>/`.
    public async publish(_project: Project, storage: IStorage, provider: IServiceProvider): Promise<PublishResult>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        const sources = await collectTodlSources(storage)
        if (sources.length === 0) return { ok: false, message: 'Nothing to publish — the project has no .todl files.' }

        const outcome = compilePackage([], sources, {
            id: manifest.id,
            version: manifest.modelVersion,
            name: manifest.name ?? manifest.id,
        })
        if (!outcome.ok || outcome.package === undefined)
            return { ok: false, message: `Publish blocked: ${outcome.errors.length} error(s). Fix them first.` }
        const pkg = outcome.package
        const doc = pkg.document

        // Assign + write mural resource keys onto icon apps before either the
        // presentation or model.json is written — pkg.document is the same object
        // BlobPackageStore persists, so the key reaches model.json.
        stampResourceKeys(doc)

        const dest = ensureMetaModelsBackend(provider)
        const base = `${manifest.id}/${manifest.modelVersion}`

        // Compile the presentation first — a missing icon blocks the publish
        // before anything is written to the backend.
        const pres = await publishPresentation(storage, dest, base, doc)
        if (!pres.ok)
            return { ok: false, message: `Publish blocked: missing icon file(s): ${pres.missing.join(', ')}.` }

        // model.json + src/ written by TODL's BlobPackageStore (the publish spine).
        await new BlobPackageStore(new StoragePackageSink(dest)).persist(pkg)
        // Ship a thin package descriptor (identity + package-level annotations) so
        // Plexus can understand the package without parsing model.json.
        const PACKAGE_NODE = 'package'
        const manifestFile: MetaModelManifestFile = {
            id: manifest.id, version: manifest.modelVersion, name: manifest.name ?? manifest.id,
            annotations: projectAnnotations(doc, PACKAGE_NODE),
        }
        await dest.WriteText(`${base}/manifest.json`, JSON.stringify(manifestFile, null, 2))
        // Keep the project's presentation dictionary current with what was published
        // (colored — matches the colored runtime bake).
        await this.writePresentation(storage, doc, true)
        return {
            ok: true,
            message: `Published ${manifest.id}@${manifest.modelVersion} (${sources.length} file(s), `
                + `presentation: ${pres.icons} icon(s)).`,
        }
    }

    // Capability entry point (the "Generate Presentation" command): compile the
    // project's .todl to a model, then write the presentation dictionary. No .todl
    // → no-op; a TODL error → leave the file untouched (the Problems dock already
    // surfaces the errors).
    public async regeneratePresentation(storage: IStorage, colored: boolean): Promise<void>
    {
        const sources = await collectTodlSources(storage)
        if (sources.length === 0) return
        const { model, diagnostics } = check(sources)
        if (diagnostics.some((d) => d.severity === Severity.Error)) return
        await this.writePresentation(storage, toJSON(model), colored)
    }

    // Write presentation.generated.mu (icons-only assets dict) from an already-
    // compiled document. `colored` selects colorful vs monochrome icon includes.
    // Shared by regeneratePresentation (honors the chosen mode) and publish (always
    // colored — the inspection .mu tracks the colored runtime bake).
    private async writePresentation(storage: IStorage, doc: TodlDocument, colored: boolean): Promise<void>
    {
        await storage.WriteText(
            MetaModelProjectFactory.PRESENTATION_FILE,
            generatePresentationAssets(doc, 'MetaModelPresentation', colored))
    }
}

// ── helpers ──
function slugify(name: string): string
{
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'meta-model'
}
