// presentation-generator.ts — pure emitter for a meta-model's presentation
// resource dictionary. No I/O, no mural import; deterministic text only. All
// model/filesystem access lives in the factory that calls this.

import { projectAnnotations, type TodlDocument, type JsonNode } from '@pragmatic-tech-ai/todl'

// The ontology-tier typeOf values presented as first-class entities. `field`
// (concept attributes) is intentionally excluded.
export enum OntologyKind
{
    Concept = 'concept',
    Relationship = 'relationship',
    Taxonomy = 'taxonomy',
    Viewpoint = 'viewpoint',
    Primitive = 'primitive',
}

const ONTOLOGY_KINDS = new Set<string>(Object.values(OntologyKind))

// Ontology-tier nodes that are presentable entities (concept/relationship/
// taxonomy/primitive), in model order.
export function ontologyEntities(model: TodlDocument): JsonNode[]
{
    return model.nodes.filter((n) => n.tier === 'Ontology' && ONTOLOGY_KINDS.has(n.typeOf))
}

// Instance-tier `class` nodes — a taxonomy term (staged with `class: true`) or a
// `class` declaration. Presented as first-class templates so a term's annotation
// icon/label renders. In model order.
export function classEntities(model: TodlDocument): JsonNode[]
{
    return model.nodes.filter((n) => n.tier === 'Instance' && n.attrs['class'] === true)
}

// Distinct icon paths across every node, sorted — the SVGs the generated
// dictionary `include`s so they are available as geometry resources to generated
// templates and author templates alike. Icons are sourced solely from `<x>@icon`
// annotation application nodes (`annotate icon { path }`); the legacy `attrs.icon`
// field form was removed.
export function distinctIcons(model: TodlDocument): string[]
{
    const set = new Set<string>()
    for (const n of model.nodes) {
        // Annotation-sourced icon: a `<x>@icon` application node (typeOf 'icon')
        // carries the path on its `path` attr.
        if (n.typeOf === 'icon') {
            const path = n.attrs['path']
            if (typeof path === 'string' && path.length > 0) set.add(path)
        }
    }
    return [...set].sort()
}

// Emit the presentation ASSET dictionary: one `include` per distinct icon plus a
// reserved seam for future base64 embedded content. No DataTemplates — every entity
// renders through Plexus's one default template. `colored` picks the icon mode:
// true → `include colored` (colored IconDefinition), false → plain `include`
// (monochrome geometry); raster is unaffected either way. This is an inspection
// artifact — nothing consumes the generated file at runtime. Deterministic: icons
// sorted. `dictName` is the `resources <Name>` block identifier (per-domain).
export function generatePresentationAssets(doc: TodlDocument, dictName: string, colored: boolean): string
{
    const includes = [...assignResourceKeys(doc)].map(([p, k]) => includeLine(p, k, colored))
    return [
        '// presentation.generated.mu — AUTOGENERATED. Do not edit.',
        '// Regenerated from the compiled model. Author templates live in presentation/*.mu.',
        '',
        `resources ${dictName} {`,
        '',
        '    // --- Icons: one geometry per distinct icon referenced by the model. ---',
        ...includes,
        '',
        '    // --- Embedded content (base64) — reserved for future assets. ---',
        '}',
        '',
    ].join('\n')
}

// A raster (bitmap) icon path — baked as a BitmapImage vs an SVG IconDefinition.
// Used by the publishers' icon include resolver; kept here beside the icon helpers.
export function isRasterIcon(path: string): boolean
{
    return /\.(png|jpe?g|webp|gif)$/i.test(path)
}

// One `include` line for a presentation `resources { … }` body (4-space indented).
// When `colored`, an SVG icon uses the `colored` keyword so the compiler's include
// resolver bakes a COLORED IconDefinition (framework svgToIconJs — geometry +
// per-shape paint inlined); otherwise a plain include → monochrome geometry. Raster
// icons are always a plain include (→ a BitmapImage); the keyword is SVG-only. The
// single source of the include syntax, shared by the standalone generator and the
// publisher.
export function includeLine(path: string, key: string, colored: boolean): string
{
    const keyword = colored && !isRasterIcon(path) ? 'colored ' : ''
    return `    include ${keyword}"${path}" as ${key}`
}

// "resources/actor-internal.svg" → "mm_icon_actor_internal". Strips the
// directory + extension, lowercases, and replaces every non-identifier run with
// a single '_', so distinct paths yield distinct keys usable as a mural resource
// key (`@mm_icon_…`).
export function iconKey(path: string): string
{
    const stem = path.replace(/^.*\//, '').replace(/\.[^.]+$/, '')
    const slug = stem.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')
    return `mm_icon_${slug}`
}

// Assign every distinct icon path a UNIQUE mural resource key. The base key is
// iconKey(path); when two paths share a stem (a/az.svg, b/az.svg) the second and
// later collisions are suffixed _2, _3, … in sorted-path order. A pure function
// of the doc's icon paths (stamping adds attrs, never paths), so every call-site
// computes the identical map with no threading. Map insertion order follows
// distinctIcons (sorted), so iterating it is sorted.
export function assignResourceKeys(doc: TodlDocument): Map<string, string>
{
    const out = new Map<string, string>()
    const used = new Map<string, number>()
    for (const path of distinctIcons(doc)) {
        const base = iconKey(path)
        const n = used.get(base) ?? 0
        used.set(base, n + 1)
        out.set(path, n === 0 ? base : `${base}_${n + 1}`)
    }
    return out
}

// The unique resource key for one icon path in this doc. Falls back to the base
// iconKey for a path not among the doc's icons (should not happen in practice).
export function resourceKeyFor(doc: TodlDocument, path: string): string
{
    return assignResourceKeys(doc).get(path) ?? iconKey(path)
}

// Write the assigned resource key onto each icon application node in place — the
// "write-back" that lands in the compiled artifact (model.json). Only annotation
// application nodes (typeOf 'icon' carrying a `path`) are stamped; a raw attrs.icon
// on a concept/instance is not an application node and is left untouched. Called
// over pkg.document before persist, so the stamped key reaches model.json.
export function stampResourceKeys(doc: TodlDocument): void
{
    const keys = assignResourceKeys(doc)
    for (const n of doc.nodes) {
        if (n.typeOf !== 'icon') continue
        const attrs = n.attrs as Record<string, unknown>
        const path = attrs['path']
        if (typeof path !== 'string' || path.length === 0) continue
        const key = keys.get(path)
        if (key !== undefined) attrs['key'] = key
    }
}

// "app-component" → "App Component". Splits on '-'/'.'/'_' and title-cases each
// word. Used as the fallback label when an entity declares no attrs.label.
export function humanize(id: string): string
{
    return id.split(/[-._]/).filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ')
}

// entityKey (prefix + id) → icon resource key, for every presentable entity
// (ontology + class) that resolves an icon. `prefix` is '' (library keyspace) or
// 'mm:' (meta-model keyspace), matching the descriptor keys the resolver looks up.
// Icon-less entities are omitted. Emitted at publish time into icon-index.json so
// load never re-derives keys.
export function buildIconIndex(doc: TodlDocument, prefix: string): Map<string, string>
{
    const out = new Map<string, string>()
    for (const n of [...ontologyEntities(doc), ...classEntities(doc)]) {
        const { icon } = resolveFacets(n, projectAnnotations(doc, n.id))
        // Both SVG (baked to a colored IconDefinition, drawn by the default template's
        // Icon) and raster (baked to a BitmapImage, drawn by its Image element) are
        // indexed; only an icon-less entity is omitted (→ the default glyph).
        if (icon === undefined) continue
        out.set(prefix + n.id, resourceKeyFor(doc, icon))
    }
    return out
}

export interface PresentationFacets { icon?: string; label: string }

// Resolves the well-known presentation facets for a node. `annotations` is the
// SP2 projected bag for that node (projectAnnotations output). The icon comes
// solely from the `icon` annotation (`annotate icon { path }`); the legacy
// attr-primary field form was removed. The label stays attr-primary, falling back
// through the annotation to humanize(id).
export function resolveFacets(node: JsonNode, annotations: Record<string, Record<string, unknown>>): PresentationFacets
{
    const annIcon = annotations['icon']?.['path']
    const icon = (typeof annIcon === 'string' && annIcon.length > 0) ? annIcon : undefined

    const attrLabel = node.attrs['label']
    const annLabel = annotations['label']?.['text']
    const label = typeof attrLabel === 'string' ? attrLabel
        : typeof annLabel === 'string' ? annLabel
            : humanize(node.id)

    return { icon, label }
}
